name: posq
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.1.2+7

environment:
  sdk: ">=2.12.0 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  charts_flutter: ^0.12.0
  fl_chart: ^0.61.0
  intl: ^0.17.0
  image_picker: ^0.8.6+3
  math_expressions: ^2.3.0
  sliding_up_panel: ^2.0.0+1
  qr_flutter: ^4.0.0
  flutter_neumorphic: ^3.2.0
  shared_preferences: ^2.0.15
  flutter_barcode_scanner: ^2.0.0
  toast: ^0.3.0
  uuid: ^3.0.6
  blue_thermal_printer: ^1.2.3
  wifi_iot: ^0.3.3
  esc_pos_printer: ^4.1.0
  fluttertoast: ^8.2.1
  syncfusion_flutter_charts: ^21.1.38
  firebase_core: ^2.9.0
  firebase_auth: ^4.4.0
  google_sign_in: ^6.1.0
  animated_text_kit: ^4.2.2
  google_sign_in_web: ^0.12.0
  file_picker: ^4.6.1
  flutter_easyloading: ^3.0.5
  firebase_dynamic_links: ^5.3.3
  im_stepper: ^1.0.1+1
 


dependency_override:
  firebase_messaging_platform_interface: 3.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0
  sqflite: ^2.0.0+4
  path: ^1.8.0
  google_fonts: 2.2.0
  change_app_package_name: ^1.1.0
  #firebase_storage: ^10.2.3
  ##firebase_messaging: ^10.0.8
  #firebase_database: ^9.0.2
  #firebase_core: ^1.10.5
  #firebase_auth: ^3.3.17
  url_launcher: ^6.0.10
  pdf: ^3.6.1
  path_provider: ^2.0.0
  printing: ^5.3.0
  dropdown_button2: ^2.1.0
  in_app_purchase: ^3.1.5


  


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/cutlery.png
    - assets/settings.png
    - assets/coming-soon.png
    - assets/user.png
    - assets/other.png
    - assets/buyer.png
    - assets/product.png
    - assets/database.png
    - assets/correct.png
    - assets/gopay.jpg
    - assets/image2.png
    - assets/logo-dana-indonesia.jpg
    - assets/logo-shopeepay.png
    - assets/link.png 
    - assets/qris.png
    - assets/ovo.png
    - assets/permatabank.png
    - assets/mandiri.png
    - assets/bca.png
    - assets/bni.png
    - assets/bri.png
    - assets/products.png
    - assets/help.png
    - assets/outlet.png
    - assets/pegawai.png
    - assets/pembeli.png
    - assets/resto.png
    - assets/retail.png
    - assets/qris.png
    - assets/barcode-scanner.png
    - assets/list.png
    - assets/icons8-barcode-100.png
    - assets/icons8-checklist-100.png
    - assets/sheryl.png
    - assets/cart1.png
    - assets/outlet1.png
    - assets/investor.png
    - assets/product1.png
    - assets/staff.png
    - assets/support.png
    - assets/transaction.png
    - assets/condiment.png
    - assets/addproduct.png
    - assets/google.png
    - assets/round-table.png
    - assets/wallet.png
    - assets/check.png
    - assets/package.png
    - assets/fifo.png


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
